[+] Custom toasts' functionality.
ElrondNetwork/dapp-core pull request #263
Opened 2022-06-16 14:34 UTC by MiroMargineanu

2022-06-16 15:13 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +  signedTransactionsToRender: any;
get type from below

2022-06-16 15:13 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +    currentTx == null ||
extract to const `invalidCurrentTx`

2022-06-16 15:13 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +const TransactionToastComponent = ({
move to _components_ subfolder

2022-06-16 15:13 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +  const customToastsFromStore = useGetCustomToasts().customToasts;
const {customToastsFromStore:  customToasts } = useGetCustomToasts();

2022-06-16 15:13 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +    setToastsIds((toastsIds: any[]) =>
check use of any

2022-06-16 15:13 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +      toastsIds.filter((toast: any) => toast.toastId !== toastId)
same

2022-06-16 15:13 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +
if type = custom return component
if type = transaction return component

2022-06-16 15:13 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +    if (total.find((item: any) => item.toastId === toast.toastId)) {
check use of any

2022-06-16 15:13 UTC, arhtudormorar commented on src/hooks/toasts/useGetCustomToasts.ts
> +  const customToasts = useSelector(customToastsSelector);
drop function and use only selector

2022-06-16 16:58 UTC, StanislavSava commented on src/UI/TransactionsToastList/index.tsx
> +    currentTx == null ||
This check is redundant

2022-06-16 16:59 UTC, StanislavSava commented on src/UI/TransactionsToastList/index.tsx
> +      const types = ['custom', 'transaction'];
these can probably can be moved to an enum

2022-06-16 16:59 UTC, StanislavSava commented on src/UI/TransactionsToastList/index.tsx
> +          {type === 'custom' && (
you can probably do a switch here, it would look better

2022-06-16 17:00 UTC, StanislavSava commented on src/UI/TransactionsToastList/index.tsx
> +        newToasts.map((toastId) => ({ toastId, type: 'transaction' }))
gotta use enums for these strings

2022-06-16 17:01 UTC, StanislavSava commented on src/UI/TransactionsToastList/index.tsx
> +      customToastsFromStore.reduce(removeToastDuplicates, toastsIds)
I think it's better to move the result of the reduce to a constant and use that in the function call

2022-06-17 12:46 UTC, StanislavSava commented on src/UI/ExplorerLink/styles.scss
> +    color: #6c757d !important;
try to avoid important

2022-06-17 12:48 UTC, StanislavSava commented on src/UI/TransactionsToastList/components/CustomToastComponent/index.tsx
> +    if (duration) {
duration != null

2022-06-17 12:52 UTC, StanislavSava commented on src/UI/TransactionToast/index.tsx
>    status,
Let's make this component a dumb component and move the logic to transactionToastComponent

2022-06-17 13:02 UTC, StanislavSava commented on src/UI/TransactionsToastList/index.tsx
> +  useEffect((): (() => void) => {
let's drop this

2022-06-17 13:03 UTC, StanislavSava commented on src/UI/TransactionsToastList/index.tsx
> +  const saveSessionStorageToasts = (): void => {
let's remove this

2022-06-17 13:03 UTC, StanislavSava commented on src/UI/TransactionsToastList/utils/removeToastDuplicates.ts
> +  if (total.find((item: ToastsType) => item.toastId === toast.toastId)) {
use uniqBy from lodash

2022-06-17 13:04 UTC, StanislavSava commented on src/UI/TransactionsToastList/utils/removeToastDuplicates.ts
> +const removeToastDuplicates = (
Let's rename this, as it adds things to the toast list

2022-06-17 13:06 UTC, StanislavSava commented on src/hooks/toasts/useHandleCustomToast.ts
> +export const useHandleCustomToast = (): useHandleCustomToastType => ({
this is not a hook function,let's rename it

2022-06-17 13:06 UTC, StanislavSava commented on src/redux/slices/toastsSlice.ts
> +          type: 'custom',
use enum

2022-06-17 13:07 UTC, StanislavSava commented on src/redux/slices/toastsSlice.ts
> +      state.customToasts = (state.customToasts || []).filter(
If we initialize the state with an empty array and make sure we don't nullify it, we can drop these checks. Also you can check for null with state?.customToasts?.filter

2022-06-17 13:10 UTC, StanislavSava requested changes
Let's change the Toast component to a dumb component

2022-06-17 13:21 UTC, arhtudormorar commented on src/UI/TransactionToast/styles.scss
> +          fill: white;
white should be a variable

2022-06-17 13:29 UTC, cipriandraghici93 approved these changes
Please see Stan's comments and you can merge the branch

2022-06-17 13:31 UTC, arhtudormorar commented on src/UI/TransactionToast/styles.scss
> +        background-color: transparent;
transparent should be variable

2022-06-17 13:31 UTC, arhtudormorar commented on src/UI/TransactionsToastList/components/CustomToastComponent/styles.scss
> +    background-color: transparent;
variable

2022-06-17 13:31 UTC, arhtudormorar commented on src/UI/TransactionsToastList/components/TransactionToastComponent/index.tsx
> +import styles from '../../styles.scss';
absolute imports?

2022-06-17 13:31 UTC, arhtudormorar commented on src/UI/TransactionsToastList/components/TransactionToastComponent/index.tsx
> +  ...props
rename `props` to `transactionToastProps`

2022-06-17 13:31 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +  const customToastsFromStore: CustomToastType[] | undefined =
definition should come from `useSelector`

2022-06-17 13:31 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +  const signedTransactionsToRender: SignedTransactionsType =
definition should be infered from below

2022-06-17 13:31 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +                message: message || '',
message ?? ''

2022-06-17 13:31 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +  const fetchSessionStorageToasts = (): void => {
no need for void return

2022-06-17 13:31 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +  useEffect((): void => {
void

2022-06-17 13:31 UTC, arhtudormorar commented on src/UI/TransactionsToastList/index.tsx
> +  useEffect((): void => {
void

2022-06-21 08:08 UTC, StanislavSava commented on src/UI/TransactionsToastList/components/Toast/components/Custom/index.tsx
> +      setTimeout(onDelete, duration);
I think we should clear the timeout on unmount, to avoid memory leaks

2022-06-21 08:09 UTC, StanislavSava commented on src/UI/TransactionsToastList/components/Toast/components/Transaction/components/Close/index.tsx
> +const Close = ({ onDelete, style, isPending }: CloseType) => {
Again, tricky name. is this a CloseButton?

2022-06-21 08:12 UTC, StanislavSava commented on src/UI/TransactionsToastList/components/Toast/components/Transaction/index.tsx
> +    signed: pendingToastData,
What if we move this guy outside of the component, with the above constants, and make the values a function that receives the changeable variables (toastId, successMessage), so we clear out the component a bit?

2022-06-21 08:15 UTC, StanislavSava commented on src/UI/TransactionsToastList/index.tsx
> +    setToastsIds((toastsIds: ToastsType[]): ToastsType[] =>
Maybe we could do this filtering inside of removeToast function and pass a callback to be called with the updated list?

removeToast(toastId, setToastsIds)

2022-06-21 08:16 UTC, StanislavSava commented on src/UI/TransactionsToastList/index.tsx
> +    }[type as string];
This logic is a bit convulted. Maybe we should just do a switch and return <Toast with different props?

2022-06-21 13:58 UTC, StanislavSava approved these changes

2022-06-21 14:04 UTC, arhtudormorar commented on src/UI/TransactionsToastList/components/Toast/components/CustomToast/styles.scss
> +  background-color: transparent;
$transparent asa cum a facut @cipriandraghici93

2022-06-21 16:09 UTC, merged